#include "HTMLWriter.h"
#include <fstream>
using namespace std;

HTMLWriter::HTMLWriter(){

    // 디폴트 파일 이름만 바꾼다
    _fileName = "NoName.html";

    // 디폴트 폰트를 지정한다
    _fontName = "굴림";
    _fontSize = 3;
    _fontColor = "black";
}

HTMLWriter::~HTMLWriter(){

}

void HTMLWriter::SetFont(const string &fontName, int fontSize, const string &fontColor){

    _fontName = fontName;
    _fontSize = fontSize;
    _fontColor = fontColor;
}

// 파일에 텍스트를 저장시킨다
void HTMLWriter::Write()
{
    // 파일을 연다
    ofstream of(_fileName.c_str());

    // HTML 헤더 부분을 저장한다
    of << "<html><head><title>This document was generated by HTMLWriter</title></head><body>";
    of << "<h1>Content</h1>";

    // 폰트 태그를 시작한다
    of << "<font name='" << _fontName << "' size='" << _fontSize << "' color='" << _fontColor << "'>";

    // 텍스트를 저장한다
    of << _content;

    // 폰트 태그를 닫는다
    of << "</font>";

    // HTML을 마무리한다
    of << "</body></html>";
}